### ISSUE TITLE
ERROR Plugin load failed: hexo-tag-vimhighlight

### ISSUE THREAD

**Issue by daxiawj** [ppwwyyxx/hexo-tag-vimhighlight#5]
After hexo ungraded to 3.0.0

hexo-tag-vimhighlight could not be loaded.

```
ERROR Plugin load failed: hexo-tag-vimhighlight
Error: Cannot find module './build/Release/shell'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/daxiawj/Workspace/newhexo/node_modules/hexo-tag-vimhighlight/node_modules/execSync/index.js:30:11)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/Users/daxiawj/Workspace/newhexo/node_modules/hexo-tag-vimhighlight/vimhl.js:5:14)
    at Object.<anonymous> (/Users/daxiawj/Workspace/newhexo/node_modules/hexo-tag-vimhighlight/vimhl.js:52:4)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/Users/daxiawj/Workspace/newhexo/node_modules/hexo/lib/hexo/index.js:213:21)
    at /Users/daxiawj/Workspace/newhexo/node_modules/hexo-tag-vimhighlight/index.js:1:85
    at /Users/daxiawj/Workspace/newhexo/node_modules/hexo/lib/hexo/index.js:229:12
    at tryCatcher (/Users/daxiawj/Workspace/newhexo/node_modules/hexo/node_modules/bluebird/js/main/util.js:24:31)
    at Promise._settlePromiseFromHandler (/Users/daxiawj/Workspace/newhexo/node_modules/hexo/node_modules/bluebird/js/main/promise.js:454:31)
    at Promise._settlePromiseAt (/Users/daxiawj/Workspace/newhexo/node_modules/hexo/node_modules/bluebird/js/main/promise.js:530:18)
    at Promise._settlePromises (/Users/daxiawj/Workspace/newhexo/node_modules/hexo/node_modules/bluebird/js/main/promise.js:646:14)
    at Async._drainQueue (/Users/daxiawj/Workspace/newhexo/node_modules/hexo/node_modules/bluebird/js/main/async.js:79:16)
    at Async._drainQueues (/Users/daxiawj/Workspace/newhexo/node_modules/hexo/node_modules/bluebird/js/main/async.js:89:10)
    at Async.drainQueues (/Users/daxiawj/Workspace/newhexo/node_modules/hexo/node_modules/bluebird/js/main/async.js:14:14)
    at process._tickCallback (node.js:355:11)
```

**Comment by ppwwyyxx** [comment]
This is a bug in execSync package.
A fix is pushed and execSync package is no longer used. Please update to hexo-tag-vimhighlight 0.1.9.
Thanks
